name: Build, Test, and Publish Docker Image
run-name: Build Docker Image and Run Test
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '../../byk-server/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'requirements.txt'
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - '../../byk-server/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
#  prepare:
#    runs-on: ubuntu-latest
#
#    outputs:
#      tags: ${{ steps.meta.outputs.tags }}
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v3
#
#    - name: Docker metadata
#      id: meta
#      uses: docker/metadata-action@v5
#      with:
#        images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}
#        tags: |
#          type=ref,event=tag
#          type=edge,branch=master,enable=false
#          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
#          type=sha,format=short,event=pr

  build:
    uses: ./.github/workflows/reusable-build-image.yml

  test:
    needs:
      - build
    uses: ./.github/workflows/reusable-run-tests.yaml.yml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}

  publish:
    needs:
      - build
      - test
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/reusable-push-image.yml
    with:
      registry: ${{ vars.DOCKER_REGISTRY }}
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
