name: Reusable Build Image
run-name: Build Docker Image
on:
  workflow_call:
    outputs:
      image_tag:
        description: 'The built image tag(s)'
        value: ${{ jobs.build.outputs.tags }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This action automatically handles your logic:
      # 1. If it's a tag (v1.0), it uses that.
      # 2. If it's master branch, it adds 'latest'.
      # 3. If it's a PR, it uses 'pr-<number>' or you can customize to SHA.
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha,format=short,enable=${{ github.event_name == 'pull_request' }}
          flavor:
            # Disables the automatic 'edge' and 'latest' defaults to keep it clean
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Upload Docker Image as Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: docker-image-artifact-temp
#          path: docker-image.tar
